/** 
* Paste one or more documents here
*/
final hotelJson = {
  "name": "Sai Kaew Beach Resort",
  "location": {
    "name": "8/1 Moo 4 Tumbon Phe Muang",
    "city": "Koh Samet",
    "country": "Thailand",
  },
  "stars": 4,
  "description":
      "The 4-star Sai Kaew Beach Resort offers comfort and convenience whether you're on business or holiday in Koh Samet. The property features a wide range of facilities to make your stay a pleasant experience. Free Wi-Fi in all rooms, daily housekeeping, gift/souvenir shop, 24-hour front desk, Wi-Fi in public areas are just some of the facilities on offer. Some of the well-appointed guestrooms feature slippers, separate living room, television LCD/plasma screen, mirror, internet access – wireless. Take a break from a long day and make use of fitness center, sauna, outdoor pool, spa, massage. No matter what your reasons are for visiting Koh Samet, Sai Kaew Beach Resort will make you feel instantly at home.",
  "room_types": [
    {
      "description": "City View",
      "type": "Standard Room",
      "price": 121.99,
      "bed_options": "1 Queen Bed",
      "sleeps_count": 2,
      "smoking_allowed": false,
      "available_rooms": 234,
      "tags": ["Jacuzzi", "WI-FI"],
    },
    {
      "description": "Cityside",
      "type": "Deluxe Room",
      "price": 146.99,
      "bed_options": "2 Queen Beds",
      "sleeps_count": 4,
      "smoking_allowed": true,
      "available_rooms": 164,
      "tags": ["Complimentary Services", "Exclusive Access", "Enhanced Views"],
    },
    {
      "description": "Mountain View",
      "type": "Suite",
      "price": 252.99,
      "bed_options": "2 Queen Beds",
      "sleeps_count": 4,
      "smoking_allowed": false,
      "available_rooms": 169,
      "tags": ["Jacuzzi", "More Space", "Better Technology"],
    },
    {
      "description": "Amenities",
      "type": "Suite",
      "price": 254.99,
      "bed_options": "2 Queen Beds",
      "sleeps_count": 4,
      "smoking_allowed": false,
      "available_rooms": 252,
      "tags": ["Seperate Living Areas", "More Space", "Upgraded Furnishings"],
    },
    {
      "description": "City View",
      "type": "Standard Room",
      "price": 99.99,
      "bed_options": "1 King Bed",
      "sleeps_count": 2,
      "smoking_allowed": true,
      "available_rooms": 276,
      "tags": ["Upgraded Furnishings"],
    },
    {
      "description": "Mountain View",
      "type": "Standard Room",
      "price": 118.99,
      "bed_options": "1 Queen Bed",
      "sleeps_count": 2,
      "smoking_allowed": true,
      "available_rooms": 223,
      "tags": ["Seperate Living Areas", "Additional Amenities"],
    },
    {
      "description": "City View",
      "type": "Budget Room",
      "price": 85.99,
      "bed_options": "2 Double Beds",
      "sleeps_count": 2,
      "smoking_allowed": false,
      "available_rooms": 198,
      "tags": ["Better Technology", "Seperate Living Areas", "More Space"],
    },
    {
      "description": "Amenities",
      "type": "Suite",
      "price": 249.99,
      "bed_options": "1 King Bed",
      "sleeps_count": 2,
      "smoking_allowed": false,
      "available_rooms": 187,
      "tags": ["Better Technology"],
    },
    {
      "description": "Amenities",
      "type": "Budget Room",
      "price": 70.99,
      "bed_options": "2 Double Beds",
      "sleeps_count": 2,
      "smoking_allowed": false,
      "available_rooms": 143,
      "tags": ["Aesthetic Appeal"],
    },
    {
      "description": "Waterfront View",
      "type": "Deluxe Room",
      "price": 139.99,
      "bed_options": "1 Queen Bed",
      "sleeps_count": 2,
      "smoking_allowed": false,
      "available_rooms": 324,
      "tags": ["Complimentary Services", "Privacy", "WI-FI"],
    },
    {
      "description": "Amenities",
      "type": "Deluxe Room",
      "price": 147.99,
      "bed_options": "1 Queen Bed",
      "sleeps_count": 2,
      "smoking_allowed": false,
      "available_rooms": 324,
      "tags": ["Additional Amenities", "Aesthetic Appeal"],
    },
    {
      "description": "City View",
      "type": "Budget Room",
      "price": 70.99,
      "bed_options": "1 Queen Bed",
      "sleeps_count": 2,
      "smoking_allowed": true,
      "available_rooms": 149,
      "tags": ["Privacy", "Aesthetic Appeal", "Seperate Living Areas"],
    }
  ],
  "rooms_number": 2885,
  "__v": 0
};
